name: Publish to npm and GitHub Packages on PR to master

on:
  pull_request:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v6

      # Setup Node.js
      - uses: actions/setup-node@v6
        with:
          node-version: "24.x"

      # Remove any pre-existing .npmrc before running yarn to prevent Yarn from reading it
      - name: Remove .npmrc
        run: |
          if [ -f .npmrc ]; then
            rm .npmrc
          fi

      # Install dependencies
      - run: yarn

      # Publish to GitHub Packages
      - name: Publish to GitHub Packages
        run: |
          # Temporarily add scope to package.json for GitHub Packages
          sed -i 's/"name": "sleek-scroll"/"name": "@Raphael2001\/sleek-scroll"/' package.json
          echo "//npm.pkg.github.com/:_authToken=\${NODE_AUTH_TOKEN}" > .npmrc
          npm publish --registry https://npm.pkg.github.com
          # Restore original package.json after publishing
          git checkout package.json
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Publish to npm (npmjs.org)
      - name: Publish to npm
        run: |
          echo "//registry.npmjs.org/:_authToken=\${NODE_AUTH_TOKEN}" > .npmrc
          npm publish --access public --registry https://registry.npmjs.org
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
