name: Update version on PR merge to master

on:
  pull_request:
    branches:
      - master
    types: [closed]

permissions:
  contents: write
  pull-requests: write

jobs:
  version-bump:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          ref: dev # Checkout the 'dev' branch
          token: ${{ secrets.PAT_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24"
          cache: "npm"

      - name: Install npm dependencies
        run: yarn

      - name: Bump package version
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          yarn version --patch --no-git-tag-version
          git commit -am "Bump version to $(jq -r '.version' package.json) [skip ci]"
          git tag "v$(jq -r '.version' package.json)"

      - name: Push changes to dev
        run: git push origin HEAD:dev --tags
